#+OPTIONS: num:nil
#+OPTIONS: html-postamble:nil
#+OPTIONS: toc:nil

* 个人信息
- 姓名：苏立权
- 性别：男
- 年龄：37
- 电话：13811820579
- 邮件：suliquanhm@hotmail.com
- 求职意向：Linux C/C++ 开发工程师
-----

* 自我介绍
有十年以上的IT从业经验；适应跨团队、高压力、快节奏的工作环境；有良好的沟通能力，
可以迅速的融入具有挑战性的工作环境；在高并发、网络编程、大流量数据处理、系统架构
设计等方面有丰富经验；主要使用语言为C/C++，主要开发平台为Linux，同时在工作中还学
习了Python、Go等编程语言；学习能力强，喜欢学习新技术，近期还参与了AI相关项目的开
发，对AI大模型的使用有一定了解。
-----

* 专业技能
- 熟悉常用的算法和数据结构；
- 熟悉多线程与多进程编程技术，熟悉常用的线程同步技术与进程间通信技术；
- 熟悉网络编程，熟悉 TCP/IP 通信原理；
- 熟悉 C/C++，熟悉 C++11，有良好的面向对象思维和编码风格；
- 熟悉 Linux 系统常用操作，熟练使用 gcc/gdb 等 Linux 下开发工具；
- 熟悉 MySQL、PostgreSQL、Redis 等数据库操作；
- 熟悉 kafka、RabbitMQ 等消息中间件；
- 熟悉 Boost、Poco、Wangle 等开发库；
- 熟悉 epoll、libev、libevnet 等高性能异步事件库；
- 熟悉 Git、SVN 等版本控制软件；
- 熟悉 Python、Go 等编程语言和相关开发框架；
-----

* 工作经历
** 2021.5 ～ 2024.6 北京世纪互联宽带数据中心有限公司 Linux C/C++/Python/Go 软件工程师
- 负责公司云平台的开发与维护
- 负责公司AI应用的技术调研与开发
- 负责云平台部署运维文档编写，AI应用设计文档编写，专利文档编写

** 2018.7 ～ 2021.4 北京柏链基石科技有限公司 Linux C/C++/Python 软件工程师
- 负责区块链相关应用开发与技术调研
- 负责设计文档编写

** 2017.7 ～ 2018.6 云易天城（北京）安全科技开发有限公司 C++ 软件工程师
- 负责DLP数据防泄漏产品的开发与专利编写
- 负责模块设计文档编写，专利文档编写

** 2016.5 ～ 2017.6 北京思锐信息技术有限公司 C++ 软件工程师
- 负责凤凰金融海外资产产品中对接美股实时数据的后台开发
- 负责模块设计文档编写

** 2013.4 ～ 2016.5 北京英进质方科技有限公司 C++ 软件工程师
- 负责公司移动Wlan上网日志留存项目调优
- 负责马来西亚电信运营商认证计费等功能开发
- 负责产品设计文档编写

** 2010.10 ～ 2013.3 北京联银通科技有限公司 C 软件工程师
- 负责在民生银行驻场开发储蓄国债项目
- 负责设计文档编写
-----

* 项目经历
** AIStorage（2023.10 ～ 2024.4）
*** 项目描述
该项目旨在构建一个类HuggingFace的大模型托管平台，主要功能包括大模型文件的存储、
分发、管理和AI终端设备内的大模型基座功能，主要使用技术有Ceph，IPFS，PyTorch，
Transformers，Flask等。

其中大模型文件的存储基于Ceph分布式存储集群，以提高文件读取速度，集群扩展性和数据
安全性，模型分发功能基于IPFS去中心化文件存储技术实现。利用IPFS的去中心化存储技术
为用户提供模型发布，下载和下载加速等功能，并且基于IPFS的原有客户端修改开发了自己
的客户端方便用户浏览管理和下载大模型文件。

大模型基座功能使用PyTorch，Transformers等原生库开发实现，主要实现功能有适配不同
模型的加载，切换，流式对话等功能，运行平台为NVIDIA发售的ARM架构的NVIDIA Jetson终
端盒子。

同时还使用Flask框架开发了一套Web Service接口用于在客户端中对模型实例进行管理和调
用模型对话功能，还有获取终端盒子中系统资源的实时监控等功能。
*** 项目职责
在该项目中主要负责大模型基座功能和Web Service的开发，同时还负责项目前期大模型相
关技术的调研和大模型文件存储分发功能中Ceph集群和IPFS网络的搭建与测试。

** 销售助手AI工具（2023.5 ～ 2023.10）
*** 项目描述
该项目旨在为销售人员提供一个可以通过AI对话的方式获取机房数据中心基本信息的销售助
手，主要使用的技术有LangChain，LlamaIndex，Flask等。

其中大模型的加载，Prompt格式化管理，数据中心的资料文档加载，还有交互过程中工具
Chain的使用等提问流程调度均使用LangChain实现。向量数据库的生成，加载和数据的匹配
策略使用LlamaIndex实现。

前端交互界面使用Vue开发，Web Service使用Flask开发实现前端界面与底层LangChain间的
交互。
*** 项目职责
在该项目中主要负责LangChain和Web Service部分功能的开发和前期LangChain与AI大模型
的技术调研。

** LCloud公有云平台（2022.8 ～ 2023.4）
*** 项目描述
该项目旨在开发一个公有云平台，用以替换掉公司当前内部使用的基于OpenStack部署的私
有云平台，同时还可以将闲置的服务器和算力以云服务、云存储、云算力的形式向外出售。

该项目核心功能源码为外部采购，我参与开发的部分为lman-cargo与lman-cmdb等外部功能
模块，主要使用技术有Go，Ansible，MetaDB等。

CMDB（Configuration Management Database）是一个逻辑数据库，包含了配置项全生命周
期的信息以及配置项之间的关系(包括物理关系、实时通信关系、非实时通信关系和依赖关
系)。

lman-cmdb项目存储与管理lcould平台中的各种配置信息，它与所有管理业务和服务流程都
紧密相联，支持这些业务的运转、发挥配置信息的价值，同时依赖于相关流程保证数据的准
确性。主要功能有设备数据采集（手动/自动），区域管理，
Cluster/Host/Tag/Storage/Network纳管功能，通知Agent支持服务分发Agent到新增Host，
纳管设备至stack。底层关系存储使用MetaDB实现，接口逻辑部分使用Go开发。

lman-cargo是Agent分发部署服务，负责Agent软件部署和管理。lman-cargo可以自动化地将
Agent软件安装到多个主机上，并对这些主机进行集中管理。用于监控、配置和管理分布式
系统中的服务器和应用程序。分发功能使用Ansible实现，通过执行不同的Playbook完成不
同类型Agent的安装部署与配置。
*** 项目职责
在该项目中主要负责lman-cmdb模块中Host纳管接口部分的逻辑功能实现和lman-cargo模块
的开发。

** Violas钱包项目（2020.5 ～ 2021.4）
*** 项目描述
该项目在Diem链的基础上进行二次开发，增加了资金池，交易所，数字银行，夸链兑换等功
能。

我负责的后台Web Service部分主要为前端提供RESTful数据接口供前端查询账户信息，交易
记录，存款/借款产品，资金池流动性状态，交易所可兑换币种，夸链可交换币种等功能，
区块链扫链服务主要用于扫描区块链实时获取交易信息供前端进行交易查询和消息推送服务
根据交易信息进行消息推送功能，数据库与缓存用于存储用户交易信息索引以提高交易信息
记录查找速度和按条件查询交易信息功能需求，日终账户结算服务用于每日结算用户相关存
款/借款产品收益与利息，并进行入库供用户进行明细查询与产品收益率计算。

后端服务整体架构为微服务架构，由Web Service提供对外唯一出口，其他内部模块间通信
使用消息队列与gRPC实现。

主要使用技术有Python、Flask、SQLAlchemy、Redis、PostgreSQL、gRPC、RabbitMQ、
Docker、Nginx。
*** 项目职责
在项目中我主要负责Violas钱包后台部分服务的开发，包括移动端和PC端的Web Service，
区块链扫链服务，日终账户结算服务，消息推送服务，数据库和缓存的操作服务。

** Seal Pay钱包项目（2019.10 ～ 2020.2）
*** 项目描述
该项目为BTC钱包项目，主要为了解决BTC链上交易打包慢的问题，使BTC钱包交易速度更快，
更符合日常小额支付使用需求。

我负责后台Web Service模块的开发，主要功能有用户管理，用户鉴权，数字货币间汇率计
算等功能。

主要使用技术有Python、Flask、Redis、MariaDB、Nginx。
*** 项目职责
在项目中主要负责Seal Pay钱包后台Web Service的开发。

** 比特币理财项目（2019.4 ～ 2019.10）
*** 项目描述·
该项目为BTC理财产品销售平台，用户可在该平台上购买第三方BTC理财产品。

我负责其中的Web Service模块的开发，为移动端提供后台数据接口。

主要使用技术有Python、Falsk、Redis、MariaDB、Nginx。
*** 项目职责
在项目中主要负责后端Web Service的开发。

** 比特币信托服务（2018.10 ～ 2019.3）
*** 项目描述
该项目为基于BTC的信托服务，用户可以使用BTC购买相关的金融信托产品进行理财或对资产
进行升值/保值操作。

其中我负责的Oracle Server模块主要的功能是为信托钱包提供支付脚本的验证与存储，该
模块包含客户端和服务端，客户端供其他端引用调用提供借口与服务端进行通信，服务端提
供后台接口服务。

主要使用技术有C++、Wangle。
*** 项目职责
在项目中主要负责Oracle Server模块的开发。

** DLP数据防泄漏产品（2017.7 ～ 2018.6）
*** 项目描述
该项目为一套完整的数据安全保护解决方案，其中包括针对整个公司网络的数据安全保护部
分和针对员工个人电脑终端的数据安全保护部分。

在该项目中我主要负责Linux服务端中部分模块的设计与开发工作，还有相关接口的RESTful
API的实现。

其中数据库指纹生成模块主要功能为按照用户配置对指定数据库中数据进行指纹生成，使用
指纹信息生成Bloom过滤器供数据库匹配引擎模块使用，支持当前普遍使用的四个数据库
MySQL，SqlServer，oracle，DB2。

数据库匹配引擎模块主要功能为使用数据库指纹生成模块生成的Bloom过滤器对截获到的文
本内容进行匹配过滤。

邮件内容发现模块主要功能为按照用户配置到对员工邮件内容进行数据爬取，并送到DLP主
程序中对爬取内容进行匹配过滤，以发现非法邮件，仅支持PST文件格式。

同时在项目中完成了数据库指纹匹配算法的专利文档，并且申请成功。
*** 项目职责
在项目中主要负责DLP产品中Linux服务端的数据库指纹生成模块、数据库匹配引擎模块、数
据库内容发现模块、邮件内容发现模块的设计与开发。

** 交易管理平台（2017.3 ～ 2017.6）
*** 项目描述
该项目为在银河证券部署上线的交易管理平台，整个项目包括使用Java开发的前端页面展示
部分和使用C++开发的后台数据采集处理部分。

我在该项目中主要负责后台数据采集处理部分的架构设计和编码实现，后期还移植了
Wireshark中TDS和DRDA协议解析的源码到项目中。

该项目采用多进程开发方式，每块采集网卡对应一个进程，使用PF_RING在网卡上进行抓包
并传递给工作线程进行处理，因为数据量比较大为了提高报文处理效率采用了多线程的实现
方式，收到的报文会根据hash算法分配到不同的工作线程中，为防止频繁申请释放内存消耗
过多的时间与制造内存碎片每个工作线程节点中都实现了环形缓冲区，用来存储上一个工作
线程处理完的结果数据，并且可以避免锁的竞争。项目中的线程使用了Boost库中线程与线
程池的实现。在完成基础模块的开发的前提下，后期还完成了Wireshark中TDS和DRDA协议解
析代码的迁移。
*** 项目职责
在项目中主要负责底层基础模块的开发，并参与项目架构的讨论与搭建。

** 海外资产美股项目（2016.5 ～ 2016.12）
*** 项目描述
该项目为凤凰金融App中投资理财模块部分的美股项目，可以让用户在应用内进行美股投资。
前端分为Android和iOS两个版本，后端使用Node实现Web后台，使用C++实现美股行情数据的
抓取，解析与处理部分，后端模块间使用TCP长链接进行通讯。

本人在项目中负责美股行情数据的解析处理部分，该部分分为两个模块，数据抓取模块和数
据解析模块，数据抓取模块只负责行情数据的抓取与备份并将行情数据传输给数据解析模块，
数据解析模块会根据规定报文格式解析行情数据，然后根据股票代码到Hash Table中查找上
一笔交易的数据，并使用新数据更新覆盖上一次的交易数据，最后存入Redis缓存供前端接
口查找调用，并发送给前端web服务供实时数据更新。
*** 项目职责
在项目中主要负责美股行情网关模块的开发工作，以及项目上线后的代码重构与Bug修复。

** 马来西亚P1 GTP报文解析项目（2016.3 ～ 2016.4）
*** 项目描述
该项目为马来西亚电信运营商P1为接入LTE网络进行用户认证需求开发的，用C语言实现在
AAA报文服务器中监听GTP-C报文数据包，根据其中的Create Session Request消息和Create
Session Response消息来判断用户的上线对接状态。

本人在项目中负责报文解析模块的架构设计与代码实现。该项目实现了一个简单的GTP-C报
文协议栈，能够对TCP协议进行部分字段解析并对建立在之上的GTP-C协议进行全字段解析，
获取其中关键字段用来匹配用户在线认证。期间使用tcpdump对网卡进行抓包并使用
Wireshark对抓到的数据包进行过滤与分析。
*** 项目职责
负责GTP报文解析模块的设计、开发与调试工作。

** 北京移动Wlan上网日志留存项目（2015.7 ～ 2015.10）
*** 项目描述
该项目是北京移动为了保存Wlan用户上网痕迹而发起的，整体结构分为数据采集和数据展示
两部分，后端数据采集部分使用C语言实现并部署在多个数据采集机上，前端数据展示部分
使用java实现，前后端间的数据传输使用文件传输。

本人在项目中负责后端数据采集部分的开发与测试，数据源由北京移动机房分光而来，因数
据量巨大为防止丢包并提高抓包速度，使用了PF_RING抓包工具在网卡上直接抓包并传到进
程内进行匹配处理，避免数据积压进程内部采用了多线程实现，每个工作线程内部有一个双
缓冲队列，避免锁竞争。数据包的匹配原则为用户上行数据包中的四元组数据与下行数据包
中的四元组数据能够对应上就算一条上网行为，此时需记下该条上网行为的四元组数据和会
话开始结束时间还有该私网IP对应的公网IP和端口，之后将该条记录写入到文件中，待稍后
传给前端数据展示模块。
*** 项目职责
负责项目的架构设计、开发与调试工作，以及后期功能增加与项目维护。

** 马来西亚Time PCC项目（2015.5 ～ 2016.3）
*** 项目描述
该项目以3GPP规范中PCC架构为基础，实现了其中PCRF(Policy and Charging Rules
Function)部分，以完成固网用户上线时的策略下发，策略变更与用户下线功能。各个模块
采用多进程设计，模块内部业务处理采用多线程设计。模块间使用socket建立连接，并用内
部定义报文进行消息通信。其中DUI模块与SNIFF模块在同一台服务器上且消息单一，使用有
名管道进行通信。

该项目核心为在DUI模块内部维护一个用户Hash Table用于维护用户的基本信息与上线信息，
供其他模块进行数据的查询下发与维护。
*** 项目职责
负责项目架构设计与部分模块的开发调试工作，功能需求的后期升级与维护。

** 联通包罗万象业务（2014.1 ～ 2014.4）
*** 项目描述
该项目为联通手机短信互动类业务，在手机SIM卡应用菜单中进行开通并使用。功能涵盖聊
天交友，答题互动，信息查询等，从中可以赚取金豆购买虚拟道具。还可以通过开放平台接
口连接第三方公司对平台业务进行扩展。
*** 项目职责
负责用户信息管理部分代码开发与测试。

** 传统短信平台项目（2013.4 ～ 2013.7）
*** 项目描述
该项目为与国内三大移动运营商合作的短信业务，由用户转发种子短信换取积分兑换礼品。
该平台模块由C++编写，网络通信使用Socket和ACE框架编写，后台数据库为Oracle，数据库
操作使用OCI编写，由于局点话单数据量很大该系统使用多线程开发。
*** 项目职责
负责根据需求修改业务模块代码逻辑与单元测试。

** 民生银行储蓄国债项目（2010.10 ～ 2012.12）
*** 项目描述
该项目为储蓄国债在民生银行实施项目，根据银行实际情况对储蓄国债平台进行本地部署与
交易开发。并根据银行个性化需求进行新增服务的设计与开发。还会对系统进行调优，使用
LondRunner对平台进行压力测试，交易量为50并发，最终将交易响应时间由1.8秒/笔调优到
0.7秒/笔。该项目由C语言开发，使用Oracle数据库，数据库操作使用Pro*C编写，通信层由
Socket编写和tuxedo中间件处理。
*** 项目职责
项目负责国债相关交易的实现与代码的优化，和文档的编写。
-----

* 教育背景
- 2007 ～ 2010 北京联合大学信息学院 软件技术（大专）
-----

* 致谢
感谢您花时间阅读我的简历。
